# Generated by Django 6.0.3 on 2026-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('name', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
