# Generated by Django 6.0.3 on 2026-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleTable',
        ),
    ]
